# 线程数
WORKER_SIZE: 256

# 版本号
VERSION: ${fullVersion}

# jsoup超时时间（秒）
JSOUP_TIMEOUT_SECOND: 10

# 程序运行超时时间（分钟）
APP_TIMEOUT_MINUTE: 10

IRREGULAR_VERBS_EXCEL:
  # 不规则动词变化表excel名称
  EXCEL_NAME: irregularVerbs.xlsx
  # 不规则动词变化表sheet名称
  SHEET_NAME: irregularVerbs

CUSTOMIZE_RULES_EXCEL:
  # 不规则动词变化表excel名称
  EXCEL_NAME: customizeRules.xlsx
  # 不规则动词变化表sheet名称
  SHEET_NAME: customizeRules

TASK_EXCEL:
  # 待处理单词excel名称
  EXCEL_NAME: word.xlsx
  # 待处理单词sheet名称
  SHEET_NAME: word

RESULT_EXCEL:
  # 结果excel名称
  EXCEL_NAME: result.xlsx
  # 结果excel sheet名称
  SHEET_NAME: result

# 有多个结果是否显示多个结果(true/false，默认true)
IS_SHOW_MULTIPLE_RESULT: false

# 符合自定义规则且字典不能查出来的词的颜色（默认黑色0x000000）
# 黄色
CUSTOMIZE_RULE_MATCHED_NOT_FOUND_IN_DICT_TASK_COLOR_IN_RGB: 0xFFFF66

# 符合自定义规则且字典能查出来的词的颜色（默认黑色0x000000）
CUSTOMIZE_RULE_MATCHED_FOUND_IN_DICT_TASK_COLOR_IN_RGB: 0xC0C0C0

# 超时错误的词的颜色（默认黑色0x000000）
# 红色
SOCKET_TIMEOUT_TASK_COLOR_IN_RGB: 0xFF6666

# 不符合自定义规则且字典能查出来的词的颜色（默认黑色0x000000）
# 蓝色
CUSTOMIZE_RULE_NOT_MATCHED_TASK_COLOR_IN_RGB: 0x66FFFF

# 符合不规则动词变化表的词的颜色（默认黑色0x000000）
# 绿色
IRREGULAR_VERBS_MATCHED_TASK_COLOR_IN_RGB: 0x66FF66

# 其他错误的颜色（默认黑色0x000000）
# 粉色
UNKNOWN_TASK_COLOR_IN_RGB: 0xFF66B2

# 规定时间内没有执行完的任务的颜色（默认黑色0x000000）
# 淡紫色
APP_TIMEOUT_TASK_COLOR_IN_RGB: 0xE5CCFF